### ISSUE TITLE
--addtional-properties option

### ISSUE THREAD

**Issue by RyosukeCla** [azu/create-validator-ts#12]
I want `addtional-properties` option.

**Comment by azu** [comment]
Do you means that you want to configure `additionalProperties` on [ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator/blob/80bba1cb2b893edc81fce08accddae76390d5156/src/Config.ts#L1-L15)?

https://github.com/azu/create-validator-ts/blob/8c4d8976548185ea81ef0628d67e133975078025/src/create-validator-ts.ts#L31

It is reasonable that each ts-json-schema-generator options are implemented as CLI flag.

```
    --expose
    --topRef
    --jsDoc
    --sortProps
    --strictTuples
    --skipTypeCheck
    --encodeRefs
    --additionalProperties
```

📝 [meow](https://github.com/sindresorhus/meow) support `--no-` prefix.

**Comment by RyosukeCla** [comment]
> Do you means that you want to configure additionalProperties

that is exactly correct!!
