### ISSUE TITLE
Support for JSDoc default values

### ISSUE THREAD

**Issue by loopingrage** [azu/create-validator-ts#32]
It would be awesome if one could annotate a field with JSDoc `@default` like this:
```
export type Config = BaseConfig & {
  sparkplug: {
    groupIds: string[]
    systemTopic: string
  }
  advanced?: {
    /**
     *  @default true
     */
    disableSomeFeature?: boolean
  }
}
```
And have the resulting validator JSON Schema include the default value. In this way, the validator could be also used to apply default values to user-provided JSON inputs.

Has this been considered? Would you consider this in scope for this library? If so, would you consider a PR with this feature?

**Comment by azu** [comment]
https://github.com/azu/create-validator-ts/releases/tag/v6.0.0 support `useDefault` by default.
